management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
#        https://incheol-jung.gitbook.io/docs/study/srping-in-action-5th/chap-16.
        include: health, refresh, env

spring:
  application:
    name: config-client
  profiles:
    active: develop
  kafka:
    bootstrap-servers: http://my-kafka:9092
  cloud:
    bus:
      ack:
        enabled: true
        refresh:
          enabled: true
#  config:
#    import: "configserver:"

server:
  port: 8081
